# Use root/example as user/password credentials
version: "3.1"

services:
  client:
    container_name: react_client
    build: ./client
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - mern_app
    environment:
      API_URL: http://localhost:9090/api/v1

  api_server:
    container_name: node_server
    build: ./server
    command: npm run start
    ports:
      - 9090:4000
    networks:
      - mern_app
    depends_on:
      - mongo_node
    environment:
      PORT: 4000
      DB_CNN: mongodb://mongo_node/wdw

  mongo_node:
    container_name: mongo_for_server
    image: mongo
    restart: always
    networks:
      - mern_app
    ports:
      - 7777:27017
networks: 
  mern_app:
    driver: bridge
